version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/code/frontend
  backend:
    build: ./backend
    ports:
      - "3000:5000"
    volumes:
      - ./backend:/code/backend
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
