version: "3.9"
services:
  login-app:
    build: ./frontend/loginApp
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/loginApp:/app
      - '/app/node_modules'
    stdin_open: true
  cocktail-app:
    build: ./frontend/cocktailApp
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/cocktailApp:/app
      - '/app/node_modules'
    stdin_open: true
  backend:
    build: ./backend
    ports:
      - "3000:5000"
    volumes:
      - ./backend:/code/backend
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
